### ISSUE TITLE
Asm .spn Files - No Sound

### ISSUE THREAD

**Issue by PeterUveges** [eh2k/vcvrack-fv1-emu#13]
Hello !
I'ts Peter From Budapest.
Your module is really cool, ive used it to test my fv1 algorithms :)

Yesterday i realized something strange about the module.
Some Spin Asm .spn files can not be loaded correctly.

For example i can open a simple old fv1 demo .spn file, and it works perfectly,
but after i open it in spin ASM and save the file again as an .spn file, 
it cannot be loded. The module loads the file but no sound.

Is that a common problem ?

For example, here is a simple fv1 demo file. It worked originally.
I saved it again from spin asm, without any modifications,
and then no sound:
https://drive.google.com/file/d/1yKX5JU9YPBRfbCXt3EQ3Y0gNAVrg5sYw/view?usp=sharing

Thanks For help :)

**Comment by eh2k** [comment]
Hello @PeterUveges,

The SPN Files have to be ASCII/UTF8 encoded. 
I think you can fix it, by simple opening and saving the spn file with the windows notepad.

**Comment by PeterUveges** [comment]
Thanks for help !
Now It Works !

I have another question but i will open another
thread for it.

Problem solved ! 
Thanks Again !
